# Generated by Django 5.1.2 on 2024-10-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('classMonitor', 'ClassMonitor'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
