# Generated by Django 5.1.3 on 2024-11-18 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('specialization', models.CharField(choices=[('Salon', 'Salon Cleaning'), ('Kitchen', 'Kitchen Cleaning'), ('Gardening', 'Gardening Cleaning'), ('Backyard', 'Backyard Cleaning'), ('Poultry', 'Poultry Cleaning'), ('Glasss', 'Glasss Cleaning'), ('Loundry', 'Loundry Cleaning')], max_length=50)),
                ('rating', models.FloatField(default=0.0)),
                ('chief', models.OneToOneField(limit_choices_to={'role': 'Chief'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_as_chief', to='account.user')),
                ('members', models.ManyToManyField(limit_choices_to={'role': 'Member'}, related_name='group_as_member', to='account.user')),
            ],
        ),
    ]
