# Generated by Django 5.1.3 on 2024-11-25 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('specialization', models.CharField(choices=[('Salon', 'Salon Cleaning'), ('Kitchen', 'Kitchen Cleaning'), ('Gardening', 'Gardening Cleaning'), ('Backyard', 'Backyard Cleaning'), ('Poultry', 'Poultry Cleaning'), ('Glass', 'Glass Cleaning'), ('Laundry', 'Laundry Cleaning')], max_length=50)),
                ('rating', models.FloatField(default=0.0)),
                ('chief', models.OneToOneField(limit_choices_to={'profile__role': 'Chief'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_as_chief', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(limit_choices_to={'profile__role': 'Member'}, related_name='group_as_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Chief', 'Chief'), ('Member', 'Member')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
