# Generated by Django 5.1.2 on 2024-10-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_remove_group_members_cleaninggroup'),
        ('tasks', '0002_remove_task_date_task_assigned_date_task_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
