# Generated by Django 5.1.3 on 2024-11-26 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taskTeams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_type', models.CharField(choices=[('Salon', 'Salon Cleaning'), ('Kitchen', 'Kitchen Cleaning'), ('Gardening', 'Gardening Cleaning'), ('Backyard', 'Backyard Cleaning'), ('Poultry', 'Poultry Cleaning'), ('Glass', 'Glass Cleaning'), ('Laundry', 'Laundry Cleaning')], max_length=50)),
                ('address', models.TextField()),
                ('house_number', models.CharField(max_length=50)),
                ('cleaning_date', models.DateField()),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved_by_client', models.BooleanField(default=False)),
                ('approved_by_admin', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('assigned_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taskTeams.group')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
